version: '3'

volumes:
  db_vol:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app

  db:
    image: mysql/mysql-server:8.0
    container_name: nest-dev-db3
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nest_db3
    ports:
      - '3307:3306'
    volumes:
      - db_vol:/var/lib/mysql
